### ISSUE TITLE
Wishlist: -p with percentage, ETA, when possible

### ISSUE THREAD

**Issue by larswirzenius** [rjek/fling#11]
It'd be great for -p output to say how much is left and long the transfer will still take.

When stdin is from a file, not a pipe, this should be possible.

**Comment by rjek** [comment]
Nice idea, might require some juggling of the extisting code however.  I'll add it to the todo list!

**Comment by rjek** [comment]
I've implemented something that does approximately this - can you give it a whirl?

**Comment by larswirzenius** [comment]
I can see it working. However, the output format is long enough that it requires a wider terminal than what I usually have. The clean way to fix this would be to query the terminal for its width and adapt (truncate) output so it fits, but that gets a little tricky in all the details, and might not be worth it. The easy solution would be to shorten the output so it usually works for most terminals. Maybe changb

"%d days, %d hours, %d minutes, %d seconds"

to

"%dd%dh%dmin%ds"? Possibly with a little whitespace?

**Comment by rjek** [comment]
I've made the whole status updates more succinct,  should always fit within 80 columns until you're shipping multiple exabytes.

**Comment by larswirzenius** [comment]
I'd test this, but:

```
gcc -o fling -O2 -Wall -Wextra -pedantic -std=c99 -lm -lrt fling.c
fling.c:149:5: error: expected identifier or ‘(’ before ‘return’
     return snprintf(buf, bufz, "%ds", seconds);
     ^~~~~~
fling.c:150:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
make: *** [Makefile:5: fling] Error 1
```


5171c0db765e01d6c9dbef32113b00897cf813a6 is the commit I have.

**Comment by larswirzenius** [comment]
Removing the extra } on line 145 gives me a working program.

The shortened progress message works for me.

**Comment by rjek** [comment]
Oops.  That's my text editor trying to be helpful :/  Fixed!

**Comment by larswirzenius** [comment]
Confirmed.
