### ISSUE TITLE
Permissions are 000 when using ssh mode

### ISSUE THREAD

**Issue by larswirzenius** [rjek/fling#12]
I ran this:

```
fling -vp exolobe2:sid.img < sid.img
```

On exolobe2, I get this:

```
---------- 1 liw liw 4.0G Dec  7 09:01 sid.img
```

Ideally, the input file's permissions would be copied, but since fling is designed to take input from stdin, including pipes, those aren't always available. For consistency, I suggest the output file is always created with the same permissions, but they should be usable, without being insecure. Can fling set them to 0600?

**Comment by rjek** [comment]
This is a regression from when I added the -o option (which is now used when flinging over ssh) - I don't set the mode on the file when opening with O_CREAT.

We could fstat() the input fd and try to use the same permissions on the created file, preying umask protects us from the possible insanity of asking an unnamed pipe for its mode?

**Comment by larswirzenius** [comment]
I think I'd prefer fling to always just set mode to 0600, or 0640 limited by umask, so it's consistent.

**Comment by rjek** [comment]
I believe this is now fixed, if you can confirm?  It will always use mode 00640.

**Comment by larswirzenius** [comment]
I'm afraid it doesn't work for me:

10:38 exolobe1:~/.../fling [master]$ rm -f ~/tmp/output*
10:39 exolobe1:~/.../fling [master]$ < README.md ./fling localhost:tmp/output
10:39 exolobe1:~/.../fling [master]$ ls -l ~/tmp/output*
---------- 1 liw liw 3239 Dec  9 10:39 /home/liw/tmp/output
10:39 exolobe1:~/.../fling [master]$

**Comment by rjek** [comment]
Hmm, this exact test works for me:
rjek@balustrade:~/git/fling$ FLING_REMOTE_EXE=/home/rjek/git/fling/fling ./fling -vp localhost:/tmp/test < README.md
trying ::1 47907... unable to connect: Connection refused
trying 127.0.0.1 47907... connected.
splicing didn't work (input not a pipe?), trying sendfile instead.
3.2 kiB (3239 bytes) transferred in 771.93 ms, 4.1 kiB/sec.
rjek@balustrade:~/git/fling$ ls -l /tmp/test 
-rw-r----- 1 rjek rjek 3239 Dec  9 09:07 /tmp/test

Did you copy the new fling binary to where the "remote" end can find it?

**Comment by larswirzenius** [comment]
Oh dang, I am a dunce. I did indeed forget to make sure the update fling binary was installed.

More specifically, I typoed its name when installing. It was installed as ~/bin/fing.

I confirm the mode bits get set correctly now.
