### ISSUE TITLE
-p results in garbage on screen after xfer

### ISSUE THREAD

**Issue by larswirzenius** [rjek/fling#3]
I think the -p option results in garbage on screen after a transfer:

    18:03 exolobe1:~/.../fling [master]$ ./fling -p exolobe2 8000 < ~/data/v-i/v-i.img 
    18:05 exolobe1:~/.../fling [master]$  in 188478.91 seconds, 22.2 kB/sec. 

Note the "in 188478.91 seconds, 22.2 kB/sec." which is left over after the transfer finishes and that the beginning of the line is overwritten by my prompt.

Suggested fix: write out a newline at the end of the transfer before ending the program. This would leave the whole progress report visible.

Also, is the duration correct? 1.9 million seconds seems a lot longer than what I thought it took.

**Comment by rjek** [comment]
Hmm, it should be erasing the process and printing out a whole new fresh line at termination.  Does this occur if you pass -pv too?  (ie, verbose mode)

**Comment by larswirzenius** [comment]
18:05 exolobe1:~/.../fling [master]$ ./fling -pv exolobe2 8000 < ~/data/v-i/v-i.img 
    trying 10.0.0.70 8000... connected.
    splicing not possible: Invalid argument, trying sendfile
    4 GB (4294967296 bytes) transferred in 41.94 seconds, 97.7 MB/sec.c. 
    18:14 exolobe1:~/.../fling [master]$ 

With -v it looks ok.

**Comment by rjek** [comment]
OK that is certainly an avenue to check then, thanks!

**Comment by rjek** [comment]
I believe both issues raised here (nonsense seconds, and failure to erase the progress when -v is not passed) are fixed in master.  Can you confirm?

**Comment by larswirzenius** [comment]
Can confirm.
